SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS report;
DROP TABLE IF EXISTS oops_tag;
DROP TABLE IF EXISTS ooh_tag;
DROP TABLE IF EXISTS tag_usage_stats;
DROP TABLE IF EXISTS bookmark;
DROP TABLE IF EXISTS report_category;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS record_history;
DROP TABLE IF EXISTS user_auth;
DROP TABLE IF EXISTS login_history;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS oops_record;
DROP TABLE IF EXISTS ooh_record;
DROP TABLE IF EXISTS notice_board;
DROP TABLE IF EXISTS follow;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS auth_list;
DROP TABLE IF EXISTS member;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS member (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
member_id VARCHAR(255) NOT NULL UNIQUE,
member_pw VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
name VARCHAR(255) NOT NULL,
birth DATE NOT NULL,
gender VARCHAR(1) NOT NULL,
user_state VARCHAR(1) NULL,
sign_up_date DATE NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report_category (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_list (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
auth_name VARCHAR(30),
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tag (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
tag_name VARCHAR(30),
tag_type VARCHAR(30),
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notice_board (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modify_date DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    is_deleted CHAR(1) NOT NULL DEFAULT 'N',
    user_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_notice_user FOREIGN KEY (user_id) REFERENCES member(id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS ooh_record (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
is_private VARCHAR(1),
title VARCHAR(255) NOT NULL,
content VARCHAR(2000) NOT NULL,
ai_answer VARCHAR(2000),
create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
modify_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
is_deleted VARCHAR(1),
user_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_ooh_user FOREIGN KEY (user_id) REFERENCES member(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS oops_record (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
is_private VARCHAR(1),
title VARCHAR(255) NOT NULL,
content VARCHAR(2000) NOT NULL,
ai_answer VARCHAR(2000),
create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
modify_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
is_deleted VARCHAR(1),
user_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_oops_user FOREIGN KEY (user_id) REFERENCES member(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS comments (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
content VARCHAR(255) NOT NULL,
create_date DATETIME,
is_deleted VARCHAR(1),
oops_id BIGINT UNSIGNED NULL,
ooh_id BIGINT UNSIGNED NULL,
user_id BIGINT UNSIGNED NOT NULL,
notice_id BIGINT UNSIGNED NULL,
PRIMARY KEY (id),
CONSTRAINT FK_comments_user FOREIGN KEY (user_id) REFERENCES member(id),
CONSTRAINT FK_comments_notice FOREIGN KEY (notice_id) REFERENCES notice_board(id),
CONSTRAINT FK_comments_oops FOREIGN KEY (oops_id) REFERENCES oops_record(id),
CONSTRAINT FK_comments_ooh FOREIGN KEY (ooh_id) REFERENCES ooh_record(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_history (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
login_success_date DATETIME,
login_ip VARCHAR(255),
login_is_succeed VARCHAR(1) NOT NULL,
user_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_loginhistory_user FOREIGN KEY (user_id) REFERENCES member(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_auth (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id BIGINT UNSIGNED NOT NULL,
auth_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_userauth_user FOREIGN KEY (user_id) REFERENCES member(id),
CONSTRAINT FK_userauth_auth FOREIGN KEY (auth_id) REFERENCES auth_list(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS record_history (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
count_date DATETIME,
record_type VARCHAR(1),
record_count INT,
user_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_count_user FOREIGN KEY (user_id) REFERENCES member(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS likes (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
oops_id BIGINT UNSIGNED NULL,
ooh_id BIGINT UNSIGNED NULL,
user_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_likes_user FOREIGN KEY (user_id) REFERENCES member(id),
CONSTRAINT FK_likes_oops FOREIGN KEY (oops_id) REFERENCES oops_record(id),
CONSTRAINT FK_likes_ooh FOREIGN KEY (ooh_id) REFERENCES ooh_record(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS follow (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
follower_id BIGINT UNSIGNED NOT NULL,
followee_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_follow_follower FOREIGN KEY (follower_id) REFERENCES member(id),
CONSTRAINT FK_follow_followee FOREIGN KEY (followee_id) REFERENCES member(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bookmark (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
oops_id BIGINT UNSIGNED NULL,
ooh_id BIGINT UNSIGNED NULL,
user_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_bookmark_user FOREIGN KEY (user_id) REFERENCES member(id),
CONSTRAINT FK_bookmark_oops FOREIGN KEY (oops_id) REFERENCES oops_record(id),
CONSTRAINT FK_bookmark_ooh FOREIGN KEY (ooh_id) REFERENCES ooh_record(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS report (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
report_date DATETIME NOT NULL,
state VARCHAR(1),
category_id BIGINT UNSIGNED NOT NULL,
user_id BIGINT UNSIGNED NOT NULL,
ooh_id BIGINT UNSIGNED NULL,
oops_id BIGINT UNSIGNED NULL,
comment_id BIGINT UNSIGNED NULL,
PRIMARY KEY (id),
CONSTRAINT FK_report_category FOREIGN KEY (category_id) REFERENCES report_category(id),
CONSTRAINT FK_report_user FOREIGN KEY (user_id) REFERENCES member(id),
CONSTRAINT FK_report_ooh FOREIGN KEY (ooh_id) REFERENCES ooh_record(id),
CONSTRAINT FK_report_oops FOREIGN KEY (oops_id) REFERENCES oops_record(id),
CONSTRAINT FK_report_comment FOREIGN KEY (comment_id) REFERENCES comments(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tag_usage_stats (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
record_type VARCHAR(1) NOT NULL,
period_start DATETIME,
period_end DATETIME,
usage_count INT,
tag_id BIGINT UNSIGNED NOT NULL,
user_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT FK_tagusage_tag FOREIGN KEY (tag_id) REFERENCES tag(id),
CONSTRAINT FK_tagusage_user FOREIGN KEY (user_id) REFERENCES member(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS oops_tag (
tag_id BIGINT UNSIGNED NOT NULL,
oops_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (tag_id, oops_id),
CONSTRAINT FK_tag_TO_oops_tag FOREIGN KEY (tag_id) REFERENCES tag(id),
CONSTRAINT FK_oops_TO_oops_tag FOREIGN KEY (oops_id) REFERENCES oops_record(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ooh_tag (
tag_id BIGINT UNSIGNED NOT NULL,
ooh_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (tag_id, ooh_id),
CONSTRAINT FK_tag_TO_ooh_tag FOREIGN KEY (tag_id) REFERENCES tag(id),
CONSTRAINT FK_ooh_TO_ooh_tag FOREIGN KEY (ooh_id) REFERENCES ooh_record(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;